### ISSUE TITLE
Undefined array key "user_id"

### ISSUE THREAD

**Issue by k7n2g** [MusabDev/animated-epic-php-user-management-system#1]
Hi cant register to database from register form  get this error   Undefined array key "user_id"   in /welcome.php on line 62   i know user_id is a value not a key  can you help fix this please, the lines from welcome.php 62 
   $sql = "SELECT * FROM users WHERE id='{$_SESSION["user_id"]}'";
            $result = mysqli_query($conn, $sql);
            if (mysqli_num_rows($result) > 0) {
                while ($row = mysqli_fetch_assoc($result, )) {

**Comment by MusabDev** [comment]
Hello,
I think the SESSION is not set. Check whether the session is set or not, If not redirect the user to the welcome.php file. And, I saw another error in your code

Here you don't need that `,`
`while ($row = mysqli_fetch_assoc($result, )) {`
Just make it like this
`while ($row = mysqli_fetch_assoc($result)) {`

**Comment by MusabDev** [comment]
Please let me know if your problem is fixed or not. Otherwise, I am going to close the issue.

**Comment by k7n2g** [comment]
Hi i think this [file "/etc/apache2/modsecurity.d/owasp-modsecurity-crs  may have something to do with the problem working on it  will come back asap

**Comment by MusabDev** [comment]
OK. Alright

**Comment by k7n2g** [comment]
Okay working now caused by me using PHP7.2 had to upgrade to PHP8.1 for some reason   and stop modsecurity  thanks for the help i am only just starting on php

**Comment by MusabDev** [comment]
OK. You're Welcome.
