### ISSUE TITLE
ERROR AT SIGNUP

### ISSUE THREAD

**Issue by ardhixs30** [MusabDev/animated-epic-php-user-management-system#2]
Error at signup form

[![Screenshot-2022-06-21-16-40-28.png](https://i.postimg.cc/ncVG3Y5R/Screenshot-2022-06-21-16-40-28.png)](https://postimg.cc/c6j3HYdw)

**Comment by MusabDev** [comment]
Check your database and sql query.

**Comment by ardhixs30** [comment]
> 

Not. I tried Forgot Password and Login, it worked without problems
[![Screenshot-2022-06-22-07-11-09.png](https://i.postimg.cc/2jMqRq5Y/Screenshot-2022-06-22-07-11-09.png)](https://postimg.cc/w35xDjJ4)

**Comment by MusabDev** [comment]
I mean check your database if the id column has auto increment.

**Comment by ardhixs30** [comment]
> 

Data not entered in database.

AI
[![Screenshot-2022-06-22-17-12-58.png](https://i.postimg.cc/tJYBRKCP/Screenshot-2022-06-22-17-12-58.png)](https://postimg.cc/wRYX0bNT)

**Comment by MusabDev** [comment]
Can you run your SQL query in the SQL tab for testing if your SQL query is good or not

**Comment by MusabDev** [comment]
The issue was inactive.
